(() => {
  "use strict";
  const $=id=>document.getElementById(id),q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const VERSION="6.1.6";
  const menuItems=[
    ["dashboard","Dashboard","ภาพรวมการลงเวลา","▦"],["attendance","รายละเอียดเวลาทำงาน","ค้นหาและตรวจเวลาพนักงาน","◷"],["schedule","ปฏิทินจัดกะ","จัดกะรายเดือน","▣"],["review","รายการรอตรวจสอบ","Missing IN / OUT และรายการผิดปกติ","⚠"],["report","ศูนย์รายงาน","CSV Excel และ Print/PDF","▤"],["smart-assistant","ผู้ช่วยวิเคราะห์","สรุปข้อมูล Time-Clock","✦"],
    ["admin-center","HR Admin Center","ศูนย์บริหารระบบ","◆"],["admin-employees","ข้อมูลพนักงาน","Employee Directory","♟"],["admin-shifts","ตั้งค่ากะทำงาน","Shift Master","◫"],["admin-holidays","วันหยุดนักขัตฤกษ์","Holiday Master","◈"],["admin-users","User และ Scope","สิทธิ์ผู้ใช้งาน","♙"],["admin-import","นำเข้าพนักงาน","Import CSV","⇧"],["admin-time-import","นำเข้าข้อมูลลงเวลา","MobileTA Text Import","⇩"],["admin-audit","Audit Log","ประวัติการเปลี่ยนแปลง","⌁"],["system-settings","System Settings","Theme Developer และ Connection","⚙"]
  ];
  let selected=0,lastProfileKey="";
  const app=()=>window.TimeClockApp;
  const role=()=>($("roleBadge")?.textContent||"VIEWER").trim();
  const email=()=>($("sidebarUserEmail")?.textContent||"-").trim();
  const name=()=>($("sidebarUserName")?.textContent||email()).trim();
  function go(page){const el=q(`.nav-item[data-page="${page}"]`);if(el&&!el.classList.contains("hidden"))el.click();else app()?.switchPage?.(page);closeCommand();}

  function mountStatus(){if($("platformStatusbar"))return;const bar=document.createElement("div");bar.id="platformStatusbar";bar.className="platform-statusbar";bar.innerHTML=`<span id="sbConnDot" class="dot"></span><span id="sbEnv" class="status-pill">PROD</span><span id="sbRole">VIEWER</span><span id="sbEmail" class="hide-mobile">-</span><span class="status-spacer"></span><span id="sbRpc" class="hide-mobile">Supabase Ready</span><span>v${VERSION}</span>`;document.body.appendChild(bar);setInterval(()=>{if($("sbRole"))$("sbRole").textContent=role();if($("sbEmail"))$("sbEmail").textContent=email();const online=navigator.onLine;$("sbConnDot")?.classList.toggle("offline",!online);const key=`${role()}|${email()}`;if(email()!=="-"&&key!==lastProfileKey){lastProfileKey=key;document.dispatchEvent(new CustomEvent("timeclock:profile-ready",{detail:{role:role(),email:email()}}));}},700);}
  function mountCommand(){if($("commandBackdrop"))return;const el=document.createElement("div");el.id="commandBackdrop";el.className="command-backdrop hidden";el.innerHTML=`<div class="command-panel"><div class="command-input-wrap"><span>⌕</span><input id="commandInput" class="command-input" placeholder="ค้นหาเมนู รหัส หรือชื่อพนักงาน..." autocomplete="off"><span class="command-kbd">ESC</span></div><div id="commandResults" class="command-results"></div></div>`;document.body.appendChild(el);el.addEventListener("click",e=>{if(e.target===el)closeCommand()});$("commandInput").addEventListener("input",renderCommand);$("commandInput").addEventListener("keydown",e=>{const items=qa(".command-item",$("commandResults"));if(e.key==="ArrowDown"){e.preventDefault();selected=Math.min(selected+1,items.length-1);renderActive(items);}else if(e.key==="ArrowUp"){e.preventDefault();selected=Math.max(selected-1,0);renderActive(items);}else if(e.key==="Enter"&&items[selected])items[selected].click();});}
  function renderActive(items){items.forEach((x,i)=>x.classList.toggle("active",i===selected));items[selected]?.scrollIntoView({block:"nearest"});}
  function employeeItems(term){if(term.length<2)return[];const raw=app()?.state?.filters?.employees||[];return raw.map(x=>typeof x==="string"?{emp_code:x,full_name:""}:x).filter(x=>`${x.emp_code||x.employee_id||x.EmployeeId||""} ${x.full_name||x.name||""}`.toLowerCase().includes(term)).slice(0,8).map(x=>({emp:String(x.emp_code||x.employee_id||x.EmployeeId||""),name:String(x.full_name||x.name||"")}));}
  function renderCommand(){const term=$("commandInput").value.trim().toLowerCase();selected=0;const visible=new Set(qa(".nav-item:not(.hidden)").map(x=>x.dataset.page));const menus=menuItems.filter(x=>visible.has(x[0])&&(!term||`${x[1]} ${x[2]} ${x[0]}`.toLowerCase().includes(term)));const employees=employeeItems(term);const res=$("commandResults");if(!menus.length&&!employees.length){res.innerHTML=`<div class="command-empty">ไม่พบข้อมูลที่ตรงกับ “${term}”</div>`;return;}res.innerHTML=`${menus.length?`<div class="command-section-label">เมนู</div>${menus.map((x,i)=>`<button class="command-item ${i===0?"active":""}" data-go="${x[0]}"><span class="command-item-icon">${x[3]}</span><span class="command-item-text"><strong>${x[1]}</strong><small>${x[2]}</small></span></button>`).join("")}`:""}${employees.length?`<div class="command-section-label">พนักงาน</div>${employees.map(x=>`<button class="command-item" data-command-employee="${x.emp}"><span class="command-item-icon">♙</span><span class="command-item-text"><strong>${x.emp} ${x.name}</strong><small>เปิดรายละเอียดเวลาทำงาน</small></span></button>`).join("")}`:""}`;qa("[data-go]",res).forEach(b=>b.onclick=()=>go(b.dataset.go));qa("[data-command-employee]",res).forEach(b=>b.onclick=async()=>{go("attendance");const input=$("attendanceGridSearch");if(input){input.value=b.dataset.commandEmployee;input.dispatchEvent(new Event("input"));}else if(app()?.loadAttendance)await app().loadAttendance();});}
  function openCommand(){if(!$("commandBackdrop"))return;$("commandBackdrop").classList.remove("hidden");$("commandInput").value="";renderCommand();setTimeout(()=>$("commandInput")?.focus(),20);}
  function closeCommand(){$("commandBackdrop")?.classList.add("hidden");}
  function mountDrawer(){if($("notificationDrawer"))return;const d=document.createElement("aside");d.id="notificationDrawer";d.className="notification-drawer";d.innerHTML=`<div class="drawer-head"><div><small>TIME-CLOCK V6</small><h3>การแจ้งเตือน</h3></div><button id="drawerClose" class="btn btn-light btn-icon">×</button></div><div class="drawer-tabs"><button class="drawer-tab active">ทั้งหมด</button><button class="drawer-tab" data-drawer-go="review">รอตรวจสอบ</button><button class="drawer-tab" data-drawer-go="schedule">ตารางกะ</button></div><div class="drawer-body"><div class="notification-empty">กำลังโหลดการแจ้งเตือน...</div></div>`;document.body.appendChild(d);$("drawerClose").onclick=()=>d.classList.remove("open");qa("[data-drawer-go]",d).forEach(b=>b.onclick=()=>{go(b.dataset.drawerGo);d.classList.remove("open");});}
  function mountProfile(){if($("profileMenu"))return;const p=document.createElement("div");p.id="profileMenu";p.className="profile-menu hidden";p.innerHTML=`<div class="profile-head"><div class="profile-avatar" id="profileAvatar">TC</div><div class="profile-meta"><strong id="profileName">-</strong><span id="profileEmail">-</span><span id="profileRole">VIEWER</span></div></div><hr><button class="profile-action" data-profile-go="smart-assistant">✦ ผู้ช่วยวิเคราะห์</button><button class="profile-action" data-profile-go="system-settings">⚙ System Settings</button><button class="profile-action" id="profileTheme">◐ เปลี่ยนธีม</button><button class="profile-action" id="profileLogout">↪ ออกจากระบบ</button>`;document.body.appendChild(p);qa("[data-profile-go]",p).forEach(b=>b.onclick=()=>{go(b.dataset.profileGo);p.classList.add("hidden")});$("profileTheme").onclick=()=>$("themeToggleBtn")?.click();$("profileLogout").onclick=()=>$("logoutBtn")?.click();}
  function enhanceTopbar(){const old=q(".global-search");old?.classList.add("hidden-important");const right=q(".topbar-right");if(!right||$("shellSearchBtn"))return;const b=document.createElement("button");b.id="shellSearchBtn";b.className="btn btn-light shell-search-trigger desktop-only";b.innerHTML="<span>⌕ ค้นหาทั้งระบบ</span><kbd>Ctrl K</kbd>";b.onclick=openCommand;right.insertBefore(b,right.firstChild);const roleEl=$("roleBadge");if(roleEl){roleEl.style.cursor="pointer";roleEl.title="เปิดโปรไฟล์ผู้ใช้งาน";roleEl.onclick=toggleProfile;}}
  function toggleProfile(){const p=$("profileMenu");if(!p)return;p.classList.toggle("hidden");$("profileName").textContent=name();$("profileEmail").textContent=email();$("profileRole").textContent=role();$("profileAvatar").textContent=(name().slice(0,2)||"TC").toUpperCase();}
  function bind(){document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand();}if(e.key==="Escape"){closeCommand();$("notificationDrawer")?.classList.remove("open");$("profileMenu")?.classList.add("hidden");}});$("notificationBtn")?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();$("notificationDrawer")?.classList.toggle("open");window.TimeClockFunctional?.loadNotifications?.();},true);document.addEventListener("click",e=>{if(!e.target.closest("#profileMenu")&&!e.target.closest("#roleBadge"))$("profileMenu")?.classList.add("hidden");});}
  function init(){mountStatus();mountCommand();mountDrawer();mountProfile();enhanceTopbar();bind();document.documentElement.dataset.platformVersion=VERSION;}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
