(() => {
  const $=id=>document.getElementById(id), safe=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  const key="timeclock_report_jobs_v55";
  const names={attendance:"รายละเอียดเวลาทำงาน",schedule:"ตารางจัดกะรายเดือน",review:"รายการรอตรวจสอบ",summary:"สรุป Dashboard",late:"มาสายและกลับก่อน"};
  let downloads=new Map();
  function client(){return window.TimeClockApp?.state?.client || window.supabaseClient || null}
  function val(id){return $(id)?.value||""}
  function thaiDateTime(v){try{return new Intl.DateTimeFormat("th-TH",{dateStyle:"short",timeStyle:"medium"}).format(new Date(v))}catch{return v}}
  function jobs(){try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return []}}
  function saveJobs(a){localStorage.setItem(key,JSON.stringify(a.slice(0,30)));renderJobs()}
  function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`}
  function makeCsv(rows){return "\uFEFF"+rows.map(r=>r.map(csvCell).join(",")).join("\n")}
  function createDownload(filename,csv){const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);downloads.set(filename,url);const a=document.createElement("a");a.href=url;a.download=filename;a.click()}
  function renderJobs(){const body=$("reportJobsBody");if(!body)return;const a=jobs();body.innerHTML=a.length?a.map(j=>`<tr><td>${safe(thaiDateTime(j.created_at))}</td><td>${safe(j.name)}</td><td>${safe(j.range)}</td><td>${Number(j.rows||0).toLocaleString("th-TH")}</td><td><span class="job-status ${safe(j.status)}">${j.status==="completed"?"สำเร็จ":j.status==="failed"?"ไม่สำเร็จ":"กำลังทำงาน"}</span></td><td>${j.status==="completed"?`<button class="report-file-link" data-redownload="${safe(j.filename)}">${safe(j.filename)}</button>`:"-"}</td></tr>`).join(""):`<tr><td colspan="6" class="report-empty">ยังไม่มีประวัติการส่งออก</td></tr>`}
  function setDefaults(){const now=new Date(),end=now.toISOString().slice(0,10),start=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10);if(!val("reportStart"))$("reportStart").value=start;if(!val("reportEnd"))$("reportEnd").value=end;renderJobs()}
  async function rpc(name,args){const c=client();if(!c)throw new Error("ยังไม่ได้เชื่อมต่อ Supabase");const {data,error}=await c.rpc(name,args);if(error)throw error;return data||[]}
  const fmtDate=v=>v?new Intl.DateTimeFormat("th-TH").format(new Date(v)):"";
  const fmtTime=v=>{if(!v)return "";const text=String(v);if(!text.includes("T")&&!text.includes(" "))return text.slice(0,5);const d=new Date(v);return Number.isNaN(d.getTime())?text.slice(0,5):d.toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit",hour12:false})};
  async function build(type){const start=val("reportStart"),end=val("reportEnd"),zone=val("reportZone")||null,dept=val("reportDepartment")||null;if(!start||!end)throw new Error("กรุณาเลือกช่วงวันที่");
    if(type==="attendance"||type==="late"){const data=await rpc("ta_get_attendance_detail",{p_start_date:start,p_end_date:end,p_zone:zone,p_department:dept,p_emp_codes:null,p_attendance_statuses:null,p_schedule_statuses:null});const filtered=type==="late"?data.filter(r=>Number(r.late_minutes||0)>0||Number(r.early_leave_minutes||0)>0):data;const shifts=window.TimeClockApp?.state?.filters?.shifts||[];const shiftTime=(r,side)=>{const code=r.effective_shift_code||r.assigned_shift_code||r.shift_code||r.auto_shift_code;const master=shifts.find(s=>String(s.shift_code||"").toUpperCase()===String(code||"").toUpperCase())||{};return side==="start"?(r.effective_shift_start_time||r.assigned_shift_start_time||r.shift_start_time||master.start_time):(r.effective_shift_end_time||r.assigned_shift_end_time||r.shift_end_time||master.end_time)};return [["วันที่","รหัสพนักงาน","ชื่อ-นามสกุล","หน่วยงาน","พื้นที่","เวลาเริ่มกะ","เวลาสิ้นสุดกะ","กะ","เวลาเข้า","เวลาออก","ชั่วโมงสุทธิ","มาสาย(นาที)","กลับก่อน(นาที)","สถานะ"],...filtered.map(r=>[fmtDate(r.work_date),r.emp_code,r.full_name,r.department,r.zone,fmtTime(shiftTime(r,"start")),fmtTime(shiftTime(r,"end")),r.effective_shift_code||r.assigned_shift_code||r.shift_code||r.auto_shift_code,fmtTime(r.actual_in_at||r.first_in),fmtTime(r.actual_out_at||r.last_out),Number(r.net_work_minutes||0)/60,r.late_minutes||0,r.early_leave_minutes||0,r.attendance_result||r.attendance_status])];}
    if(type==="schedule"){const month=start.slice(0,7)+"-01";const data=await window.TimeClockShiftAPI.getMonthlySchedule(window.TimeClockApp,{p_month:month,p_zone:zone,p_department:dept,p_emp_codes:null,p_schedule_statuses:null});return [["วันที่","รหัสพนักงาน","ชื่อ-นามสกุล","หน่วยงาน","พื้นที่","ประเภทวัน","กะตั้งต้น","กะแนะนำ","กะที่กำหนด","กะใช้งานจริง","ยืนยันแล้ว","ความมั่นใจ"],...data.map(r=>[fmtDate(r.work_date),r.emp_code,r.full_name,r.department,r.zone,r.day_type||"WORKDAY",r.auto_shift_code,r.suggested_shift_code,r.assigned_shift_code,r.effective_shift_code,r.is_confirmed?"ใช่":"ไม่ใช่",r.suggestion_confidence])];}
    if(type==="review"){const data=await window.TimeClockShiftAPI.getReview(app(),{p_start_date:start,p_end_date:end,p_zone:zone,p_department:dept,p_emp_codes:null,p_issue_types:null});return [["วันที่","รหัสพนักงาน","ชื่อ-นามสกุล","หน่วยงาน","กะตั้งต้น","กะแนะนำ","ความมั่นใจ","เวลาเข้า","เวลาออก","ประเภทปัญหา"],...data.map(r=>[fmtDate(r.work_date),r.emp_code,r.full_name,r.department,r.auto_shift_code,r.suggested_shift_code,r.suggestion_confidence,fmtTime(r.actual_in_at||r.first_in),fmtTime(r.actual_out_at||r.last_out),r.issue_type||r.review_reason])];}
    if(type==="summary"){const raw=await rpc("ta_get_dashboard_overview",{p_start_date:start,p_end_date:end,p_zone:zone,p_department:dept});const d=Array.isArray(raw)?raw[0]||{}:raw;return [["รายการ","จำนวน"],["พนักงานทั้งหมด",d.total_employees],["รายการทั้งหมด",d.total_rows],["ลงเวลาครบ",d.complete_time_rows],["ไม่พบเวลาเข้า",d.missing_in_rows],["ไม่พบเวลาออก",d.missing_out_rows],["ไม่มีข้อมูลเวลา",d.absent_rows??d.no_time_rows],["รอตรวจสอบ",d.need_review_rows],["ทำงานวันหยุด",d.worked_on_offday_rows],["กะยืนยันแล้ว",d.confirmed_rows]];}
    throw new Error("ไม่พบประเภทรายงาน");
  }
  async function run(type){const id=crypto.randomUUID?.()||String(Date.now()),start=val("reportStart"),end=val("reportEnd"),filename=`${type}_${start}_${end}.csv`;let a=jobs();a.unshift({id,name:names[type],range:`${start} ถึง ${end}`,rows:0,status:"running",filename,created_at:new Date().toISOString()});saveJobs(a);try{window.TimeClockApp?.showLoading?.("กำลังสร้างรายงาน...");const rows=await build(type),csv=makeCsv(rows);createDownload(filename,csv);a=jobs().map(j=>j.id===id?{...j,rows:Math.max(0,rows.length-1),status:"completed"}:j);saveJobs(a);window.TimeClockApp?.toast?.("สร้างรายงานเรียบร้อย","success")}catch(e){a=jobs().map(j=>j.id===id?{...j,status:"failed",error:e.message}:j);saveJobs(a);window.TimeClockApp?.toast?.(e.message||"สร้างรายงานไม่สำเร็จ","error")}finally{window.TimeClockApp?.hideLoading?.()}}
  document.addEventListener("click",e=>{const b=e.target.closest("[data-run-report]");if(b)run(b.dataset.runReport);const r=e.target.closest("[data-redownload]");if(r){const url=downloads.get(r.dataset.redownload);if(url){const a=document.createElement("a");a.href=url;a.download=r.dataset.redownload;a.click()}else window.TimeClockApp?.toast?.("กรุณาสร้างรายงานใหม่ เนื่องจากไฟล์เดิมไม่อยู่ในหน่วยความจำแล้ว","error")}});
  document.addEventListener("DOMContentLoaded",()=>{$("reportRefreshJobsBtn")?.addEventListener("click",renderJobs);$("reportClearJobsBtn")?.addEventListener("click",()=>{localStorage.removeItem(key);renderJobs()});setDefaults()});
  window.TimeClockReports={renderJobs,setDefaults};
})();
