(function(){
  "use strict";
  const VERSION="6.14.82";
  const CFG_KEY="ta_supabase_config_v1";
  const SESSION_KEY="ta_employee_portal_session_v61482";
  const TEAM_KEY="ta_employee_portal_team_v61482";
  const DEFAULT={url:"https://lryojaccbbbgdbpjstld.supabase.co",key:"sb_publishable_xxYLeNtxgeWoE0o5GNOwDg_QXfiFy_Y"};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
  let client=null,me=null,calendar=[],requests=[],notifications=[],scheduleMonth=new Date();let requestFilter="";
  const urlTeam=new URLSearchParams(location.search).get("team")||"";
  let teamToken=urlTeam||localStorage.getItem(TEAM_KEY)||"";
  if(urlTeam)localStorage.setItem(TEAM_KEY,urlTeam);
  const session=()=>localStorage.getItem(SESSION_KEY)||"";
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
  const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
  const addDays=(s,n)=>{const d=new Date(`${s}T00:00:00`);d.setDate(d.getDate()+n);return iso(d);};
  const fmtDate=s=>{if(!s)return"-";const d=new Date(`${String(s).slice(0,10)}T00:00:00`);return d.toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"});};
  const fmtDateTime=s=>{if(!s)return"-";const d=new Date(s);return Number.isNaN(d.getTime())?String(s):d.toLocaleString("th-TH",{dateStyle:"short",timeStyle:"short"});};
  const fmtTime=v=>{if(!v)return"-";const x=String(v);const m=x.match(/(?:T|\s)(\d{2}:\d{2})/)||x.match(/^(\d{2}:\d{2})/);return m?m[1]:x.slice(0,5);};
  function config(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(CFG_KEY)||"{}")};}catch(_){return DEFAULT;}}
  function toast(msg,type="info"){const el=$("portalToast");el.textContent=msg;el.className=`portal-toast ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add("hidden"),3500);}
  function loading(on,text="กำลังโหลด..."){const el=$("portalLoading");$("portalLoadingText").textContent=text;el.classList.toggle("hidden",!on);}
  function friendly(e){const m=String(e?.message||e||"");if(m.includes("PORTAL_LOGIN_INVALID"))return"รหัสพนักงานหรือ PIN ไม่ถูกต้อง";if(m.includes("PORTAL_LOCKED_15_MINUTES"))return"กรอก PIN ผิดเกินกำหนด ระบบล็อกชั่วคราว 15 นาที";if(m.includes("ACTIVATION_CODE_INVALID"))return"Activation Code ไม่ถูกต้อง";if(m.includes("ACTIVATION_CODE_EXPIRED"))return"Activation Code หมดอายุ กรุณาขอ Code ใหม่จาก Manager";if(m.includes("PORTAL_EMPLOYEE_NOT_IN_TEAM"))return"รหัสพนักงานไม่อยู่ในทีมของ Link นี้";if(m.includes("PORTAL_NOT_ENABLED"))return"HR ยังไม่ได้เปิดสิทธิ์ Employee Portal";if(m.includes("PIN_TOO_EASY"))return"PIN ง่ายเกินไป กรุณาตั้งเลขอื่น";if(m.includes("PIN_CANNOT_MATCH_EMPLOYEE_ID"))return"PIN ห้ามตรงกับเลขท้ายรหัสพนักงาน";if(m.includes("PIN_MUST_BE_6_DIGITS"))return"PIN ต้องเป็นตัวเลข 6 หลัก";if(m.includes("PORTAL_SESSION_INVALID_OR_EXPIRED"))return"Session หมดอายุ กรุณาเข้าสู่ระบบใหม่";return m||"เกิดข้อผิดพลาด";}
  async function rpc(name,args={}){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
  function setAuthTab(tab){document.querySelectorAll("[data-auth-tab]").forEach(b=>b.classList.toggle("active",b.dataset.authTab===tab));$("portalActivateForm").classList.toggle("hidden",tab!=="activate");$("portalLoginForm").classList.toggle("hidden",tab!=="login");}
  function deviceLabel(){return `${navigator.platform||"Mobile"} • ${String(navigator.userAgent||"").slice(0,80)}`;}
  async function checkTeam(){if(!teamToken){$("portalTeamName").textContent="เปิดจาก Link/QR ของ Manager เพื่อ Activate ครั้งแรก";return false;}try{const d=await rpc("ta_portal_team_public_v61482",{p_team_token:teamToken});if(d?.valid){$("portalTeamName").textContent=`ทีมของ ${d.manager_display_name||"Manager"}`;return true;}$("portalTeamName").textContent="Link ทีมไม่ถูกต้องหรือถูกเปลี่ยนแล้ว";return false;}catch(e){$("portalTeamName").textContent="ตรวจสอบ Link ไม่สำเร็จ";return false;}}
  function showAuth(){me=null;$("portalApp").classList.add("hidden");$("portalAuth").classList.remove("hidden");}
  function showApp(){renderProfile();$("portalAuth").classList.add("hidden");$("portalApp").classList.remove("hidden");navigate("home");}
  function renderProfile(){const name=me?.full_name||me?.emp_code||"พนักงาน";$("portalEmployeeName").textContent=name;$("portalEmployeeMeta").textContent=[me?.emp_code,me?.position_name,me?.department].filter(Boolean).join(" • ");$("portalAvatar").textContent=String(name).replace(/\s+/g,"").slice(0,2)||"พน";$("portalTodayDate").textContent=new Date().toLocaleDateString("th-TH",{weekday:"long",day:"numeric",month:"long",year:"numeric"});}
  async function restore(){const t=session();if(!t)return false;try{me=await rpc("ta_portal_me_v61482",{p_session_token:t});showApp();await refreshAll();return true;}catch(e){localStorage.removeItem(SESSION_KEY);showAuth();return false;}}
  async function activate(e){e.preventDefault();if(!teamToken)return toast("กรุณาเปิดจาก Link/QR ของ Manager","warning");const pin=$("portalNewPin").value,confirm=$("portalConfirmPin").value;if(pin!==confirm)return toast("PIN และยืนยัน PIN ไม่ตรงกัน","error");loading(true,"กำลังเปิดใช้งาน Employee Portal...");try{const r=await rpc("ta_portal_activate_v61482",{p_team_token:teamToken,p_emp_code:$("portalActivateEmp").value.trim(),p_activation_code:$("portalActivationCode").value.trim(),p_new_pin:pin,p_device_label:deviceLabel()});localStorage.setItem(SESSION_KEY,r.session_token);me=r;toast("เปิดใช้งานเรียบร้อย","success");showApp();await refreshAll();}catch(err){toast(friendly(err),"error");}finally{loading(false);}}
  async function login(e){e.preventDefault();loading(true,"กำลังเข้าสู่ระบบ...");try{const r=await rpc("ta_portal_login_v61482",{p_team_token:null,p_emp_code:$("portalLoginEmp").value.trim(),p_pin:$("portalLoginPin").value.trim(),p_device_label:deviceLabel()});localStorage.setItem(SESSION_KEY,r.session_token);me=r;showApp();await refreshAll();}catch(err){toast(friendly(err),"error");}finally{loading(false);}}
  async function logout(){const t=session();localStorage.removeItem(SESSION_KEY);try{if(t)await rpc("ta_portal_logout_v61482",{p_session_token:t});}catch(_){}showAuth();setAuthTab("login");}
  function dayMeta(r){const day=String(r?.day_type||"").toUpperCase(),code=String(r?.effective_shift_code||"").toUpperCase();if(day==="LEAVE"||code==="LV")return{label:"ลา",tone:"leave"};if(r?.is_public_holiday||day==="PUBLIC_HOLIDAY"||code==="HOL")return{label:"นักขัตฤกษ์",tone:"holiday"};if(r?.is_weekly_off||day==="WEEKLY_OFF"||String(r?.is_workday)==="false")return{label:"วันหยุด",tone:"off"};const st=String(r?.calculation_status||"").toUpperCase();if(st.includes("ABSEN"))return{label:"ขาดงาน",tone:"danger"};if(Number(r?.late_minutes||0)>0)return{label:`สาย ${Number(r.late_minutes)} นาที`,tone:"late"};if(Number(r?.early_leave_minutes||0)>0)return{label:`กลับก่อน ${Number(r.early_leave_minutes)} นาที`,tone:"early"};return{label:"ปกติ",tone:"normal"};}
  function specialLabel(r){const m=String(r?.work_mode_code||"").toUpperCase();return({NORMAL_LATE_CUSTOMER:"กะปกติ + งานลูกค้าช่วงดึก",SPLIT_WAIT_NIGHT:"กะเช้า + รอเข้ากะดึก",HOUR_BASED:"กะนับชั่วโมง"})[m]||"";}
  function row(date){return calendar.find(x=>String(x.work_date).slice(0,10)===String(date).slice(0,10));}
  function renderToday(){const r=row(today()),box=$("portalTodayCard");if(!r){box.innerHTML='<div class="portal-empty">ยังไม่พบข้อมูลกะวันนี้</div>';return;}const meta=dayMeta(r),special=specialLabel(r);box.innerHTML=`<div class="portal-today-main"><div><span>${esc(meta.label)}</span><strong>${esc(r.effective_shift_code||"-")}</strong><small>${esc(r.shift_name||special||"-")}</small></div><span class="portal-shift-pill">${esc(fmtTime(r.shift_start_time))}–${esc(fmtTime(r.shift_end_time))}</span></div><div class="portal-today-times"><div><span>เวลาเข้า</span><strong>${esc(fmtTime(r.first_in||r.actual_in_at))}</strong></div><div><span>เวลาออก</span><strong>${esc(fmtTime(r.last_out||r.actual_out_at))}</strong></div></div><div class="portal-status-line">${special?`รูปแบบงาน: ${esc(special)} • `:""}${esc(meta.label)}</div>`;}
  function renderWeek(){const box=$("portalWeekStrip"),days=[];for(let i=0;i<7;i++){const d=addDays(today(),i),r=row(d),m=dayMeta(r||{}),dt=new Date(`${d}T00:00:00`);days.push(`<div class="portal-day-chip ${m.tone} ${d===today()?"today":""}"><span>${dt.toLocaleDateString("th-TH",{weekday:"short"})} ${dt.getDate()}</span><strong>${esc(r?.effective_shift_code||"-")}</strong><small>${esc(m.label)}</small></div>`);}box.innerHTML=days.join("");}
  function monthBounds(d){const y=d.getFullYear(),m=d.getMonth();return{start:`${y}-${String(m+1).padStart(2,"0")}-01`,end:iso(new Date(y,m+1,0)),days:new Date(y,m+1,0).getDate(),first:new Date(y,m,1).getDay(),title:new Date(y,m,1).toLocaleDateString("th-TH",{month:"long",year:"numeric"})};}
  function renderCalendar(){const b=monthBounds(scheduleMonth);$("portalScheduleMonthTitle").textContent=b.title;let html=["อา","จ","อ","พ","พฤ","ศ","ส"].map(x=>`<div class="portal-cal-head">${x}</div>`).join("");for(let i=0;i<b.first;i++)html+='<div class="portal-cal-day blank"></div>';for(let d=1;d<=b.days;d++){const date=`${b.start.slice(0,8)}${String(d).padStart(2,"0")}`,r=row(date),m=dayMeta(r||{});html+=`<div class="portal-cal-day ${m.tone} ${date===today()?"today":""}"><span>${d}</span><strong>${esc(r?.effective_shift_code||"-")}</strong><small>${esc(m.label)}</small><small>${esc(fmtTime(r?.shift_start_time))}–${esc(fmtTime(r?.shift_end_time))}</small></div>`;}$("portalCalendar").innerHTML=html;}
  function renderTime(){const rows=calendar.filter(r=>String(r.work_date)<=today()).sort((a,b)=>String(b.work_date).localeCompare(String(a.work_date))).slice(0,31),box=$("portalTimeList");box.innerHTML=rows.length?rows.map(r=>{const m=dayMeta(r);return `<article class="portal-time-item"><div class="portal-time-head"><strong>${esc(fmtDate(r.work_date))} • ${esc(r.effective_shift_code||"-")}</strong><span>${esc(m.label)}</span></div><div class="portal-time-grid"><div><span>เข้า</span><strong>${esc(fmtTime(r.first_in||r.actual_in_at))}</strong></div><div><span>ออก</span><strong>${esc(fmtTime(r.last_out||r.actual_out_at))}</strong></div><div><span>สาย</span><strong>${Number(r.late_minutes||0).toLocaleString("th-TH")} นาที</strong></div><div><span>กลับก่อน</span><strong>${Number(r.early_leave_minutes||0).toLocaleString("th-TH")} นาที</strong></div></div></article>`;}).join(""):'<div class="portal-empty">ยังไม่มีข้อมูลเวลาทำงาน</div>';}
  function requestStatus(s){const x=String(s||"").toUpperCase();if(["APPROVED","RESOLVED"].includes(x))return["ดำเนินการแล้ว","done"];if(["REJECTED","CANCELLED"].includes(x))return[x==="REJECTED"?"ไม่อนุมัติ":"ยกเลิก","reject"];if(x==="IN_REVIEW")return["กำลังตรวจสอบ","pending"];return["รอดำเนินการ","pending"];}
  function requestType(r){return r.request_type==="TIME_ISSUE"?"ปัญหาเวลาทำงาน":"งานกะพิเศษ";}
  function subtype(r){return({MISSING_IN:"ไม่มีเวลาเข้า",MISSING_OUT:"ไม่มีเวลาออก",WRONG_TIME:"เวลาไม่ถูกต้อง",NORMAL_LATE_CUSTOMER:"กะปกติ + งานลูกค้าช่วงดึก",SPLIT_WAIT_NIGHT:"กะเช้า + รอเข้ากะดึก",HOUR_BASED:"กะนับชั่วโมง"})[r.request_subtype]||r.request_subtype||"-";}
  function renderRequests(){let rows=requests;if(requestFilter==="PENDING")rows=rows.filter(r=>["PENDING","IN_REVIEW"].includes(String(r.status).toUpperCase()));if(requestFilter==="DONE")rows=rows.filter(r=>["APPROVED","RESOLVED","REJECTED","CANCELLED"].includes(String(r.status).toUpperCase()));const box=$("portalRequestList");box.innerHTML=rows.length?rows.map(r=>{const [sl,sc]=requestStatus(r.status);return `<article class="portal-request-item"><div class="portal-request-head"><div><strong>${esc(r.request_no||"คำขอ")} • ${esc(fmtDate(r.work_date))}</strong><span>${esc(requestType(r))} • ${esc(subtype(r))}</span></div><span class="portal-request-status ${sc}">${esc(sl)}</span></div><p>${esc(r.reason||"-")}</p>${r.decision_note?`<p><b>Manager:</b> ${esc(r.decision_note)}</p>`:""}${String(r.status).toUpperCase()==="PENDING"?`<div class="portal-request-actions"><button data-cancel-request="${esc(r.request_id)}">ยกเลิกคำขอ</button></div>`:""}</article>`;}).join(""):'<div class="portal-empty">ยังไม่มีคำขอ / แจ้งข้อมูล</div>';}
  function renderNotifications(){const box=$("portalNotificationList");box.innerHTML=notifications.length?notifications.map(n=>`<article class="portal-notification-item ${n.is_read?"":"unread"}" data-read-notification="${esc(n.notification_id)}"><div class="portal-notification-head"><strong>${esc(n.title||"แจ้งเตือน")}</strong><span>${esc(fmtDateTime(n.created_at))}</span></div><p>${esc(n.message||"")}</p></article>`).join(""):'<div class="portal-empty">ยังไม่มีแจ้งเตือน</div>';const unread=notifications.filter(n=>!n.is_read).length;$("portalNotifBadge").textContent=unread;$("portalNotifBadge").classList.toggle("hidden",!unread);}
  async function loadCalendar(){const b=monthBounds(scheduleMonth),start=[addDays(today(),-31),b.start].sort()[0],end=[addDays(today(),14),b.end].sort().reverse()[0];calendar=await rpc("ta_portal_get_my_calendar_v61482",{p_session_token:session(),p_start_date:start,p_end_date:end})||[];renderToday();renderWeek();renderCalendar();renderTime();}
  async function loadRequests(){requests=await rpc("ta_portal_get_my_requests_v61482",{p_session_token:session(),p_start_date:addDays(today(),-180),p_end_date:addDays(today(),180)})||[];renderRequests();}
  async function loadNotifications(){notifications=await rpc("ta_portal_get_notifications_v61482",{p_session_token:session(),p_limit:100})||[];renderNotifications();}
  async function refreshAll(){loading(true,"กำลังโหลดข้อมูลของคุณ...");try{await Promise.all([loadCalendar(),loadRequests(),loadNotifications()]);}catch(e){if(String(e?.message||"").includes("PORTAL_SESSION_INVALID")){localStorage.removeItem(SESSION_KEY);showAuth();toast("Session หมดอายุ กรุณาเข้าสู่ระบบใหม่","warning");}else toast(friendly(e),"error");}finally{loading(false);}}
  function navigate(name){document.querySelectorAll(".portal-view").forEach(v=>v.classList.toggle("active",v.id===`portalView${name.charAt(0).toUpperCase()+name.slice(1)}`));document.querySelectorAll("[data-portal-nav]").forEach(b=>b.classList.toggle("active",b.dataset.portalNav===name));if(name==="notifications")loadNotifications().catch(()=>{});if(name==="requests")loadRequests().catch(()=>{});}
  function fillSubtype(){const type=$("portalRequestType").value,sel=$("portalRequestSubtype"),special=type==="SPECIAL_WORK";sel.innerHTML=(special?[["NORMAL_LATE_CUSTOMER","กะปกติ + งานลูกค้าช่วงดึก"],["SPLIT_WAIT_NIGHT","กะเช้า + รอเข้ากะดึก"],["HOUR_BASED","กะนับชั่วโมง"]]:[["MISSING_IN","ไม่มีเวลาเข้า"],["MISSING_OUT","ไม่มีเวลาออก"],["WRONG_TIME","เวลาไม่ถูกต้อง"]]).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");$("portalSpecialFields").classList.toggle("hidden",!special);$("portalRequestModalTitle").textContent=special?"แจ้งทำงานกะพิเศษ":"แจ้งปัญหาเวลาทำงาน";renderEvidence();}
  function renderEvidence(){const d=$("portalRequestDate").value,r=row(d),box=$("portalRequestEvidence");if(!d){box.textContent="เลือกวันที่เพื่อดูข้อมูลกะ/เวลาในระบบ";return;}if(!r){box.textContent=`${fmtDate(d)} • ยังไม่พบข้อมูลกะ/Attendance`;return;}box.innerHTML=`<b>${esc(fmtDate(d))}</b> • กะ ${esc(r.effective_shift_code||"-")} ${esc(fmtTime(r.shift_start_time))}–${esc(fmtTime(r.shift_end_time))}<br>ระบบพบเวลาเข้า <b>${esc(fmtTime(r.first_in||r.actual_in_at))}</b> • เวลาออก <b>${esc(fmtTime(r.last_out||r.actual_out_at))}</b><br><small>ข้อมูลนี้อ่านอย่างเดียว User ไม่สามารถแก้ Raw Punch จากหน้านี้</small>`;}
  function openRequest(type="TIME_ISSUE",date=today()){const m=$("portalRequestModal");$("portalRequestType").value=type;$("portalRequestDate").value=date;$("portalRequestReason").value="";$("portalSpecialStart").value="";$("portalSpecialEnd").value="";$("portalSpecialLocation").value="";fillSubtype();m.classList.remove("hidden");}
  function closeRequest(){$("portalRequestModal").classList.add("hidden");}
  async function submitRequest(e){e.preventDefault();const type=$("portalRequestType").value,detail={source:"EMPLOYEE_PORTAL_V61482"};if(type==="SPECIAL_WORK"){detail.reported_start_time=$("portalSpecialStart").value||null;detail.reported_end_time=$("portalSpecialEnd").value||null;detail.customer_location=$("portalSpecialLocation").value.trim()||null;detail.reported_time_is_reference_only=true;}loading(true,"กำลังส่งให้ Manager...");try{await rpc("ta_portal_submit_request_v61482",{p_session_token:session(),p_work_date:$("portalRequestDate").value,p_request_type:type,p_request_subtype:$("portalRequestSubtype").value,p_reason:$("portalRequestReason").value.trim(),p_detail:detail});closeRequest();toast("ส่งให้ Manager แล้ว","success");await loadRequests();navigate("requests");}catch(err){toast(friendly(err),"error");}finally{loading(false);}}
  async function cancelRequest(id){if(!confirm("ยืนยันยกเลิกคำขอนี้?"))return;try{await rpc("ta_portal_cancel_request_v61482",{p_session_token:session(),p_request_id:id});toast("ยกเลิกคำขอแล้ว","success");await loadRequests();}catch(e){toast(friendly(e),"error");}}
  async function markRead(id){try{await rpc("ta_portal_mark_notification_read_v61482",{p_session_token:session(),p_notification_id:id});const n=notifications.find(x=>x.notification_id===id);if(n)n.is_read=true;renderNotifications();}catch(_){}}
  function bind(){document.querySelectorAll("[data-auth-tab]").forEach(b=>b.addEventListener("click",()=>setAuthTab(b.dataset.authTab)));$("portalActivateForm").addEventListener("submit",activate);$("portalLoginForm").addEventListener("submit",login);$("portalLogoutBtn").addEventListener("click",logout);$("portalRefreshBtn").addEventListener("click",refreshAll);document.addEventListener("click",e=>{const n=e.target.closest("[data-portal-nav]");if(n){navigate(n.dataset.portalNav);return;}const q=e.target.closest("[data-request-quick]");if(q){openRequest(q.dataset.requestQuick,today());return;}if(e.target.closest("[data-close-request]")){closeRequest();return;}const c=e.target.closest("[data-cancel-request]");if(c){cancelRequest(c.dataset.cancelRequest);return;}const r=e.target.closest("[data-read-notification]");if(r){markRead(r.dataset.readNotification);return;}});$("portalNewRequestBtn").addEventListener("click",()=>openRequest("TIME_ISSUE",today()));$("portalRequestType").addEventListener("change",fillSubtype);$("portalRequestDate").addEventListener("change",renderEvidence);$("portalRequestForm").addEventListener("submit",submitRequest);document.querySelectorAll("[data-request-filter]").forEach(b=>b.addEventListener("click",()=>{requestFilter=b.dataset.requestFilter;document.querySelectorAll("[data-request-filter]").forEach(x=>x.classList.toggle("active",x===b));renderRequests();}));$("portalPrevMonth").addEventListener("click",async()=>{scheduleMonth=new Date(scheduleMonth.getFullYear(),scheduleMonth.getMonth()-1,1);await loadCalendar();});$("portalNextMonth").addEventListener("click",async()=>{scheduleMonth=new Date(scheduleMonth.getFullYear(),scheduleMonth.getMonth()+1,1);await loadCalendar();});$("portalThisMonth").addEventListener("click",async()=>{scheduleMonth=new Date();await loadCalendar();});}
  async function init(){const c=config();client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});bind();await checkTeam();if(!(await restore())){showAuth();setAuthTab(teamToken?"activate":"login");}if("serviceWorker" in navigator)navigator.serviceWorker.register("./portal-sw.js").catch(()=>{});}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
