-- ============================================================================
-- SQL สำหรับตรวจสอบ
-- Time-Clock Enterprise V6.11.39
-- ============================================================================
with checks as (
  select 1 seq,'reason_master_table' check_name,case when to_regclass('public.ta_time_certification_reasons') is not null then 'PASS' else 'FAIL' end result,'Master เหตุผลการรับรองเวลา' detail
  union all select 2,'certification_columns',case when (select count(*) from information_schema.columns where table_schema='public' and table_name='ta_attendance_certifications' and column_name in('certified_start_at','certified_end_at','reason_code_snapshot','reason_name_snapshot','certified_by_email'))=5 then 'PASS' else 'FAIL' end,'คอลัมน์เวลารับรองและเหตุผล'
  union all select 3,'audit_table',case when to_regclass('public.ta_time_certification_audit') is not null then 'PASS' else 'FAIL' end,'Audit การรับรองเวลา'
  union all select 4,'reason_seed',case when (select count(*) from public.ta_time_certification_reasons where reason_code in('W01','W02','W03','W04','W05','W06','W07','W08','W09','W10','W11','W12','W13','W16','W90') and is_active)=15 then 'PASS' else 'FAIL' end,'เหตุผล Active 15 รายการ'
  union all select 5,'reason_inactive_legacy',case when (select count(*) from public.ta_time_certification_reasons where reason_code in('W14','W15') and not is_active)=2 then 'PASS' else 'FAIL' end,'W14/W15 เก็บประวัติและปิดใช้งาน'
  union all select 6,'reason_rpcs',case when to_regprocedure('public.ta_list_time_certification_reasons_v61139(boolean)') is not null and to_regprocedure('public.ta_admin_save_time_certification_reason_v61139(text,text,boolean,integer,boolean)') is not null then 'PASS' else 'FAIL' end,'RPC Master เหตุผล'
  union all select 7,'certification_range_rpc',case when to_regprocedure('public.ta_get_time_certification_range_v61139(date,date,text[])') is not null then 'PASS' else 'FAIL' end,'Set-based Team/Monthly reader'
  union all select 8,'save_revoke_rpcs',case when to_regprocedure('public.ta_save_time_certification_v61139(text,date,timestamp without time zone,timestamp without time zone,text,text)') is not null and to_regprocedure('public.ta_revoke_time_certification_v61139(text,date,text)') is not null then 'PASS' else 'FAIL' end,'Save / Revoke Time Certification'
  union all select 9,'calculation_overlay',case when to_regprocedure('public._ta_refresh_attendance_with_certification_v61139(date,date,text[])') is not null and pg_get_functiondef('public._ta_refresh_attendance_with_certification_v61139(date,date,text[])'::regprocedure) ilike '%time_certification_active%' then 'PASS' else 'FAIL' end,'Calculation Overlay โดยไม่แก้ Raw time_logs'
  union all select 10,'system_period_guard',case when pg_get_functiondef('public.ta_save_time_certification_v61139(text,date,timestamp without time zone,timestamp without time zone,text,text)'::regprocedure) ilike '%ATTENDANCE_CERTIFY%' and pg_get_functiondef('public.ta_revoke_time_certification_v61139(text,date,text)'::regprocedure) ilike '%ATTENDANCE_REVOKE_CERTIFICATION%' then 'PASS' else 'FAIL' end,'System Period + HR Admin Override'
  union all select 11,'end_after_shift_allowed',case when pg_get_functiondef('public.ta_save_time_certification_v61139(text,date,timestamp without time zone,timestamp without time zone,text,text)'::regprocedure) ilike '%p_certified_end_at<=p_certified_start_at%' and pg_get_functiondef('public.ta_save_time_certification_v61139(text,date,timestamp without time zone,timestamp without time zone,text,text)'::regprocedure) not ilike '%p_certified_end_at<=v_shift_end_at%' and pg_get_functiondef('public.ta_save_time_certification_v61139(text,date,timestamp without time zone,timestamp without time zone,text,text)'::regprocedure) not ilike '%p_certified_end_at>v_shift_end_at%' then 'PASS' else 'FAIL' end,'End ต้องมากกว่า Start แต่ไม่มีเงื่อนไขบังคับ End <= Shift End'
  union all select 12,'schedule_recalc_cert_aware',case when pg_get_functiondef('public._ta_recalculate_after_schedule_change_v61029(date,date,text[])'::regprocedure) ilike '%_ta_refresh_attendance_with_certification_v61139%' then 'PASS' else 'FAIL' end,'Schedule / Monthly / Rebuild คงผลรับรองเวลา'
  union all select 13,'attendance_trigger_cert_aware',case when pg_get_functiondef('public._ta_attendance_calc_trigger_v630()'::regprocedure) ilike '%_ta_refresh_attendance_with_certification_v61139%' then 'PASS' else 'FAIL' end,'Attendance trigger คงผลรับรองเวลา'
)
select * from checks order by seq;

select reason_code,reason_name,requires_note,sort_order,is_active from public.ta_time_certification_reasons order by sort_order,reason_code;
